import random, csv, os, msvcrt, time

trabajadores = ["Juan Pérez","María García","Carlos López","Ana Martínez","Pedro Rodríguez","Laura Hernández","Miguel Sánchez","Isabel Gómez","Francisco Díaz","Elena Fernández"]

sueldos = []

registro = []


def asignar_sueldo():
    while True:
            os.system('cls')
            for F in trabajadores:
                sueldo=random.randint(300000, 2500000)
                print("Trabajador: ",F,"\nSueldo: ",sueldo)
                time.sleep(0.6)   
            sueldos.append(sueldo)
            os.system('cls')
            print("Sueldos Entregados Con Exito!")
            time.sleep(2)
            return F
def clasificar_sueldos():
    total = 0
    TOTAL_S = 0
    while True:
        for F in trabajadores:
            for s in sueldos:    
                try:
                    print("---CLASIFICACIÓN DE SUELDOS---")
                
                    if s <= 800000:
                        os.system('cls')
                        print("SUELDOS MENORES A $800.000 TOTAL: ", total)
                        print("NOMBRE EMPLEADO   SUELDO" "\n", F, s)
                        total = total +1
                        time.sleep(2)

                    elif s>= 800000 and s<=2000000:
                        os.system('cls')
                        print("SUELDOS ENTRE $800.000 Y $2.000.000 TOTAL: ", total)
                        print("NOMBRE EMPLEADO   SUELDO" "\n", F, s)
                        total = total +1
                        time.sleep(2)

                    elif s>2000000:
                        os.system('cls')
                        print("SUELDOS MAYORES A $2.000.000 TOTAL: ", total)
                        print("NOMBRE EMPLEADO   SUELDO" "\n", F, s)
                        total = total +1
                        time.sleep(2)

                        print("TOTAL SUELDOS: ", TOTAL_S)
                        TOTAL_S=sueldos * total
                        time.sleep(2)
                    else: 
                        os.system('cls')
                        print("NO HAY SUELDOS ASIGNADOS! ASIGNE LOS SUELDOS EN LA OPCIÓN 1!")
                        time.sleep(2)
                    return
                except:
                    os.system('cls')
                    print("NO HAY SUELDOS ASIGNADOS! ASIGNE LOS SUELDOS EN LA OPCIÓN 1!")
                    time.sleep(2)
                    return

def ver_estadisticas():
    pass

def reporte_sueldos():
    pass

def salir():
    os.system('cls')
    print("\nFinalizando Programa \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa. \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa.. \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa. \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa.. \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129.115-8")
    time.sleep(0.8)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129.115-")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129.115")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129.11")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129.1")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129.")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.129")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.12")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.1")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22.")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 22")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRut 2")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nRu")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa \nR")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Roa")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni Ro")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni R")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andoni ")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Andon")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por Ando")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por And")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por An")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por A")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Por")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado Po")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado P")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollado")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrollad")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrolla")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarroll")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarrol")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarro")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesarr")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesar")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDesa")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDes")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nDe")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa... \nD")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa...")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa..")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa.")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Programa")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Program")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Progra")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Progr")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Prog")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Pro")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando Pr")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando P")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizando")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizand")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinalizan")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinaliza")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinaliz")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinali")
    time.sleep(0.1)
    os.system('cls')
    print("\nFinal")
    time.sleep(0.1)
    os.system('cls')
    print("\nFina")
    time.sleep(0.1)
    os.system('cls')
    print("\nFin")
    time.sleep(0.1)
    os.system('cls')
    print("\nFi")
    time.sleep(0.1)
    os.system('cls')
    print("\nF")
    time.sleep(0.1)
    os.system('cls')
    print("\nA")
    time.sleep(0.1)
    os.system('cls')
    print("\nAd")
    time.sleep(0.1)
    os.system('cls')
    print("\nAdi")
    time.sleep(0.1)
    os.system('cls')
    print("\nAdio")
    time.sleep(0.1)
    os.system('cls')
    print("\nAdios")
    time.sleep(0.1)
    os.system('cls')
    print("\nAdios!")
    time.sleep(1)
    os.system('cls')
    print("\n______")
    time.sleep(1)
    os.system('cls')
    print("\nAdios!")
    time.sleep(1)
    os.system('cls')
    print("\n______")
    time.sleep(1)
    os.system('cls')
    print("\nAdios!")
    time.sleep(1)
    os.system('cls')
    print("\n______")
    time.sleep(1)
    os.system('cls')
    print("\n_____")
    time.sleep(0.1)
    os.system('cls')
    print("\n____")
    time.sleep(0.1)
    os.system('cls')
    print("___")
    time.sleep(0.1)
    os.system('cls')
    print("__")
    time.sleep(0.1)
    os.system('cls')
    print("_")
    time.sleep(0.1)
    os.system('cls')
    print("°")
    time.sleep(0.1)
    os.system('cls')
    print("*")
    time.sleep(0.1)
    exit()